[package]
name = "vcxproj-parser"
version = "0.1.0"
authors = ["Zach <zachstruck@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
encoding_rs = "0.8.14"
pest = "2.0"
pest_derive = "2.0"
regex = "1"
sxd-document = "0.3.0"
