WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
simple_string = { ASCII_ALPHANUMERIC+ }
quote = _{ "'" }
quoted_char = { !quote ~ ANY }
quoted_string = @{ quote ~ quoted_char* ~ quote }
string = { simple_string | quoted_string }
lparen = _{ "(" }
rparen = _{ ")" }
group = { lparen ~ expr ~ rparen }
expr = { eq | and | group }
operand = { eq | group }
eq = { string ~ "==" ~ string }
and = { operand ~ "and" ~ operand }
main = { SOI ~ expr ~ EOI }
